/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.formulario;
import javax.swing.JFileChooser;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.*;
import java.io.FileFilter;
/**
 *
 * @author erick
 */
import javax.swing.AbstractButton;
public class designForm extends javax.swing.JPanel {

    /**
     * Creates new form designForm
     */
    public designForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        modalidadedisciplina = new javax.swing.ButtonGroup();
        tiposala = new javax.swing.ButtonGroup();
        modalidadecurso = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        admincad = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nomelb1 = new javax.swing.JLabel();
        nome1 = new javax.swing.JTextField();
        emaillb1 = new javax.swing.JLabel();
        email1 = new javax.swing.JTextField();
        senhalb1 = new javax.swing.JLabel();
        senha1 = new javax.swing.JPasswordField();
        confirmasenhalb1 = new javax.swing.JLabel();
        confirmasenha1 = new javax.swing.JPasswordField();
        cpflb1 = new javax.swing.JLabel();
        cpf1 = new javax.swing.JTextField();
        telefonelb1 = new javax.swing.JLabel();
        telefone1 = new javax.swing.JTextField();
        datanascimentolb1 = new javax.swing.JLabel();
        datanascimento1 = new javax.swing.JTextField();
        generolb1 = new javax.swing.JLabel();
        masculino1 = new javax.swing.JRadioButton();
        feminino1 = new javax.swing.JRadioButton();
        outro1 = new javax.swing.JRadioButton();
        salvarbtn1 = new javax.swing.JButton();
        alunocad = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nomelb2 = new javax.swing.JLabel();
        nomealuno = new javax.swing.JTextField();
        emaillb2 = new javax.swing.JLabel();
        emailaluno = new javax.swing.JTextField();
        senhalb2 = new javax.swing.JLabel();
        senhaaluno = new javax.swing.JPasswordField();
        confirmasenhalb2 = new javax.swing.JLabel();
        confirmasenha2 = new javax.swing.JPasswordField();
        cpflb2 = new javax.swing.JLabel();
        cpfaluno = new javax.swing.JTextField();
        telefonelb2 = new javax.swing.JLabel();
        telefonealuno = new javax.swing.JTextField();
        datanascimentolb2 = new javax.swing.JLabel();
        datanascimentoaluno = new javax.swing.JTextField();
        generolb2 = new javax.swing.JLabel();
        masculino2 = new javax.swing.JRadioButton();
        feminino2 = new javax.swing.JRadioButton();
        outro2 = new javax.swing.JRadioButton();
        salvarbtn2 = new javax.swing.JButton();
        cursocad = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nomecursolb = new javax.swing.JLabel();
        nomecurso = new javax.swing.JTextField();
        emaillb3 = new javax.swing.JLabel();
        duracaolb = new javax.swing.JLabel();
        valorlb = new javax.swing.JLabel();
        valorcurso = new javax.swing.JPasswordField();
        modalidadelb = new javax.swing.JLabel();
        presencial = new javax.swing.JRadioButton();
        ead = new javax.swing.JRadioButton();
        salvarbtn3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricaocurso = new javax.swing.JTextArea();
        duracaocurso = new javax.swing.JTextField();
        salacad = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        numerolb = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        capacidadelb = new javax.swing.JLabel();
        capacidade = new javax.swing.JTextField();
        andarlb = new javax.swing.JLabel();
        andar = new javax.swing.JTextField();
        tipolb = new javax.swing.JLabel();
        masculino4 = new javax.swing.JRadioButton();
        laboratorio = new javax.swing.JRadioButton();
        salvarbtn4 = new javax.swing.JButton();
        professorcad = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nomelb5 = new javax.swing.JLabel();
        nomeprofessor = new javax.swing.JTextField();
        emaillb5 = new javax.swing.JLabel();
        emailprofessor = new javax.swing.JTextField();
        senhalb5 = new javax.swing.JLabel();
        senhaprofessor = new javax.swing.JPasswordField();
        confirmasenhalb5 = new javax.swing.JLabel();
        confirmasenha5 = new javax.swing.JPasswordField();
        cpflb5 = new javax.swing.JLabel();
        cpfprofessor = new javax.swing.JTextField();
        telefonelb5 = new javax.swing.JLabel();
        telefoneprofessor = new javax.swing.JTextField();
        datanascimentolb5 = new javax.swing.JLabel();
        datanascimentoprofessor = new javax.swing.JTextField();
        generolb5 = new javax.swing.JLabel();
        masculino5 = new javax.swing.JRadioButton();
        feminino5 = new javax.swing.JRadioButton();
        outro5 = new javax.swing.JRadioButton();
        salvarbtn5 = new javax.swing.JButton();
        datanascimentolb8 = new javax.swing.JLabel();
        salario = new javax.swing.JTextField();
        disciplinacad = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nomedisciplinalb = new javax.swing.JLabel();
        nomedisciplina = new javax.swing.JTextField();
        duracaodisciplinalb = new javax.swing.JLabel();
        duracaodisciplina = new javax.swing.JTextField();
        modalidadedisciplinalb = new javax.swing.JLabel();
        masculino6 = new javax.swing.JRadioButton();
        feminino6 = new javax.swing.JRadioButton();
        salvarbtn6 = new javax.swing.JButton();
        contatocad = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resumo = new javax.swing.JTextArea();
        listarbtn = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(126, 153, 214));

        admincad.setBackground(new java.awt.Color(126, 153, 214));

        jPanel6.setBackground(new java.awt.Color(9, 62, 186));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LA FACULDADE");

        jLabel1.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CADASTRO ADMIN");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nomelb1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nomelb1.setForeground(new java.awt.Color(255, 255, 255));
        nomelb1.setText("NOME:");

        nome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome1ActionPerformed(evt);
            }
        });

        emaillb1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emaillb1.setForeground(new java.awt.Color(255, 255, 255));
        emaillb1.setText("E-MAIL:");

        senhalb1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        senhalb1.setForeground(new java.awt.Color(255, 255, 255));
        senhalb1.setText("SENHA:");

        senha1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        confirmasenhalb1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        confirmasenhalb1.setForeground(new java.awt.Color(255, 255, 255));
        confirmasenhalb1.setText("CONFIRME SENHA:");

        confirmasenha1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        cpflb1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cpflb1.setForeground(new java.awt.Color(255, 255, 255));
        cpflb1.setText("CPF:");

        telefonelb1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        telefonelb1.setForeground(new java.awt.Color(255, 255, 255));
        telefonelb1.setText("TELEFONE:");

        datanascimentolb1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        datanascimentolb1.setForeground(new java.awt.Color(255, 255, 255));
        datanascimentolb1.setText("DATA DE NASCIMENTO:");

        generolb1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        generolb1.setForeground(new java.awt.Color(255, 255, 255));
        generolb1.setText("GÊNERO:");

        masculino1.setBackground(new java.awt.Color(126, 153, 214));
        buttonGroup1.add(masculino1);
        masculino1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        masculino1.setForeground(new java.awt.Color(255, 255, 255));
        masculino1.setText("MASCULINO");
        masculino1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masculino1ActionPerformed(evt);
            }
        });

        feminino1.setBackground(new java.awt.Color(126, 153, 214));
        buttonGroup1.add(feminino1);
        feminino1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        feminino1.setForeground(new java.awt.Color(255, 255, 255));
        feminino1.setText("FEMININO");

        outro1.setBackground(new java.awt.Color(126, 153, 214));
        buttonGroup1.add(outro1);
        outro1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        outro1.setForeground(new java.awt.Color(255, 255, 255));
        outro1.setText("OUTRO");

        salvarbtn1.setText("SALVAR");

        javax.swing.GroupLayout admincadLayout = new javax.swing.GroupLayout(admincad);
        admincad.setLayout(admincadLayout);
        admincadLayout.setHorizontalGroup(
            admincadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(admincadLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(admincadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(admincadLayout.createSequentialGroup()
                        .addComponent(generolb1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(masculino1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(feminino1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outro1))
                    .addGroup(admincadLayout.createSequentialGroup()
                        .addComponent(datanascimentolb1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datanascimento1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(telefonelb1)
                    .addGroup(admincadLayout.createSequentialGroup()
                        .addGroup(admincadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cpflb1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(senhalb1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmasenhalb1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emaillb1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomelb1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(admincadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(email1)
                            .addComponent(nome1)
                            .addGroup(admincadLayout.createSequentialGroup()
                                .addGroup(admincadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(telefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(admincadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(confirmasenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(senha1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cpf1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)
                                .addComponent(salvarbtn1)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        admincadLayout.setVerticalGroup(
            admincadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admincadLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(admincadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomelb1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(admincadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emaillb1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(admincadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhalb1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(senha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(admincadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmasenha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmasenhalb1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(admincadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpflb1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(admincadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonelb1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(admincadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datanascimentolb1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datanascimento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(admincadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generolb1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(masculino1)
                    .addComponent(feminino1)
                    .addComponent(outro1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 282, Short.MAX_VALUE)
                .addComponent(salvarbtn1)
                .addGap(27, 27, 27))
        );

        jTabbedPane2.addTab("Admin", admincad);

        alunocad.setBackground(new java.awt.Color(126, 153, 214));

        jPanel8.setBackground(new java.awt.Color(9, 62, 186));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LA FACULDADE");

        jLabel10.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CADASTRO ALUNO");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nomelb2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nomelb2.setForeground(new java.awt.Color(255, 255, 255));
        nomelb2.setText("NOME:");

        nomealuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomealunoActionPerformed(evt);
            }
        });

        emaillb2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emaillb2.setForeground(new java.awt.Color(255, 255, 255));
        emaillb2.setText("E-MAIL:");

        senhalb2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        senhalb2.setForeground(new java.awt.Color(255, 255, 255));
        senhalb2.setText("SENHA:");

        senhaaluno.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        confirmasenhalb2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        confirmasenhalb2.setForeground(new java.awt.Color(255, 255, 255));
        confirmasenhalb2.setText("CONFIRME SENHA:");

        confirmasenha2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        cpflb2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cpflb2.setForeground(new java.awt.Color(255, 255, 255));
        cpflb2.setText("CPF:");

        telefonelb2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        telefonelb2.setForeground(new java.awt.Color(255, 255, 255));
        telefonelb2.setText("TELEFONE:");

        datanascimentolb2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        datanascimentolb2.setForeground(new java.awt.Color(255, 255, 255));
        datanascimentolb2.setText("DATA DE NASCIMENTO:");

        generolb2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        generolb2.setForeground(new java.awt.Color(255, 255, 255));
        generolb2.setText("GÊNERO:");

        masculino2.setBackground(new java.awt.Color(126, 153, 214));
        buttonGroup1.add(masculino2);
        masculino2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        masculino2.setForeground(new java.awt.Color(255, 255, 255));
        masculino2.setText("MASCULINO");
        masculino2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masculino2ActionPerformed(evt);
            }
        });

        feminino2.setBackground(new java.awt.Color(126, 153, 214));
        buttonGroup1.add(feminino2);
        feminino2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        feminino2.setForeground(new java.awt.Color(255, 255, 255));
        feminino2.setText("FEMININO");

        outro2.setBackground(new java.awt.Color(126, 153, 214));
        buttonGroup1.add(outro2);
        outro2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        outro2.setForeground(new java.awt.Color(255, 255, 255));
        outro2.setText("OUTRO");

        salvarbtn2.setText("SALVAR");
        salvarbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarbtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout alunocadLayout = new javax.swing.GroupLayout(alunocad);
        alunocad.setLayout(alunocadLayout);
        alunocadLayout.setHorizontalGroup(
            alunocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(alunocadLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(alunocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alunocadLayout.createSequentialGroup()
                        .addComponent(generolb2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(masculino2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(feminino2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outro2))
                    .addGroup(alunocadLayout.createSequentialGroup()
                        .addComponent(datanascimentolb2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datanascimentoaluno, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(telefonelb2)
                    .addGroup(alunocadLayout.createSequentialGroup()
                        .addGroup(alunocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cpflb2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(senhalb2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmasenhalb2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emaillb2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomelb2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(alunocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailaluno)
                            .addComponent(nomealuno)
                            .addGroup(alunocadLayout.createSequentialGroup()
                                .addGroup(alunocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(telefonealuno, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(alunocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(confirmasenha2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(senhaaluno, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cpfaluno, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)
                                .addComponent(salvarbtn2)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        alunocadLayout.setVerticalGroup(
            alunocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alunocadLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(alunocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomelb2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomealuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(alunocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emaillb2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailaluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(alunocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhalb2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(senhaaluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(alunocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmasenha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmasenhalb2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(alunocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpflb2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfaluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(alunocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonelb2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonealuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(alunocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datanascimentolb2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datanascimentoaluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(alunocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generolb2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(masculino2)
                    .addComponent(feminino2)
                    .addComponent(outro2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 285, Short.MAX_VALUE)
                .addComponent(salvarbtn2)
                .addGap(27, 27, 27))
        );

        jTabbedPane2.addTab("Aluno", alunocad);

        cursocad.setBackground(new java.awt.Color(126, 153, 214));

        jPanel9.setBackground(new java.awt.Color(9, 62, 186));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LA FACULDADE");

        jLabel11.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CADASTRO CURSO");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nomecursolb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nomecursolb.setForeground(new java.awt.Color(255, 255, 255));
        nomecursolb.setText("NOME:");

        nomecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomecursoActionPerformed(evt);
            }
        });

        emaillb3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emaillb3.setForeground(new java.awt.Color(255, 255, 255));
        emaillb3.setText("DESCRIÇÃO:");

        duracaolb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        duracaolb.setForeground(new java.awt.Color(255, 255, 255));
        duracaolb.setText("DURAÇÃO:");

        valorlb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        valorlb.setForeground(new java.awt.Color(255, 255, 255));
        valorlb.setText("VALOR:");

        valorcurso.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        modalidadelb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        modalidadelb.setForeground(new java.awt.Color(255, 255, 255));
        modalidadelb.setText("MODALIDADE:");

        presencial.setBackground(new java.awt.Color(126, 153, 214));
        modalidadecurso.add(presencial);
        presencial.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        presencial.setForeground(new java.awt.Color(255, 255, 255));
        presencial.setText("PRESENCIAL");
        presencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presencialActionPerformed(evt);
            }
        });

        ead.setBackground(new java.awt.Color(126, 153, 214));
        modalidadecurso.add(ead);
        ead.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ead.setForeground(new java.awt.Color(255, 255, 255));
        ead.setSelected(true);
        ead.setText("EAD");

        salvarbtn3.setText("SALVAR");
        salvarbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarbtn3ActionPerformed(evt);
            }
        });

        descricaocurso.setColumns(20);
        descricaocurso.setRows(5);
        jScrollPane1.setViewportView(descricaocurso);

        duracaocurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duracaocursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cursocadLayout = new javax.swing.GroupLayout(cursocad);
        cursocad.setLayout(cursocadLayout);
        cursocadLayout.setHorizontalGroup(
            cursocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(cursocadLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(cursocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cursocadLayout.createSequentialGroup()
                        .addGroup(cursocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomecursolb, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emaillb3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(cursocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cursocadLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(cursocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nomecurso, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cursocadLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salvarbtn3)
                                .addGap(143, 143, 143))))
                    .addGroup(cursocadLayout.createSequentialGroup()
                        .addGroup(cursocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cursocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(cursocadLayout.createSequentialGroup()
                                    .addComponent(valorlb, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(21, 21, 21))
                                .addComponent(duracaolb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(modalidadelb, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cursocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cursocadLayout.createSequentialGroup()
                                .addComponent(presencial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ead))
                            .addGroup(cursocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(duracaocurso, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(valorcurso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cursocadLayout.setVerticalGroup(
            cursocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cursocadLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cursocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomecursolb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomecurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cursocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emaillb3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(cursocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(duracaolb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duracaocurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(cursocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(valorlb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(cursocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modalidadelb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(presencial)
                    .addComponent(ead))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                .addComponent(salvarbtn3)
                .addGap(27, 27, 27))
        );

        jTabbedPane2.addTab("Curso", cursocad);

        salacad.setBackground(new java.awt.Color(126, 153, 214));

        jPanel10.setBackground(new java.awt.Color(9, 62, 186));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("LA FACULDADE");

        jLabel12.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("CADASTRO SALA");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        numerolb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        numerolb.setForeground(new java.awt.Color(255, 255, 255));
        numerolb.setText("NÚMERO:");

        numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroActionPerformed(evt);
            }
        });

        capacidadelb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        capacidadelb.setForeground(new java.awt.Color(255, 255, 255));
        capacidadelb.setText("CAPACIDADE:");

        andarlb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        andarlb.setForeground(new java.awt.Color(255, 255, 255));
        andarlb.setText("ANDAR:");

        tipolb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tipolb.setForeground(new java.awt.Color(255, 255, 255));
        tipolb.setText("TIPO:");

        masculino4.setBackground(new java.awt.Color(126, 153, 214));
        tiposala.add(masculino4);
        masculino4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        masculino4.setForeground(new java.awt.Color(255, 255, 255));
        masculino4.setText("NORMAL");
        masculino4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masculino4ActionPerformed(evt);
            }
        });

        laboratorio.setBackground(new java.awt.Color(126, 153, 214));
        tiposala.add(laboratorio);
        laboratorio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        laboratorio.setForeground(new java.awt.Color(255, 255, 255));
        laboratorio.setSelected(true);
        laboratorio.setText("LABORATÓRIO");
        laboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laboratorioActionPerformed(evt);
            }
        });

        salvarbtn4.setText("SALVAR");
        salvarbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarbtn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout salacadLayout = new javax.swing.GroupLayout(salacad);
        salacad.setLayout(salacadLayout);
        salacadLayout.setHorizontalGroup(
            salacadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(salacadLayout.createSequentialGroup()
                .addGroup(salacadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(salacadLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(salacadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(salacadLayout.createSequentialGroup()
                                .addComponent(tipolb, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(masculino4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(laboratorio))
                            .addGroup(salacadLayout.createSequentialGroup()
                                .addGroup(salacadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numerolb, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(andarlb, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(salacadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(capacidade, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(andar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addComponent(numero))
                                .addGap(278, 278, 278)
                                .addComponent(salvarbtn4))))
                    .addGroup(salacadLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(capacidadelb, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        salacadLayout.setVerticalGroup(
            salacadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salacadLayout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(salacadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numerolb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(salacadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(capacidadelb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(capacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(salacadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(andar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(andarlb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(salacadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipolb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(masculino4)
                    .addComponent(laboratorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 304, Short.MAX_VALUE)
                .addComponent(salvarbtn4)
                .addGap(27, 27, 27))
        );

        jTabbedPane2.addTab("Sala", salacad);

        professorcad.setBackground(new java.awt.Color(126, 153, 214));

        jPanel11.setBackground(new java.awt.Color(9, 62, 186));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("LA FACULDADE");

        jLabel13.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("CADASTRO PROFESSOR");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nomelb5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nomelb5.setForeground(new java.awt.Color(255, 255, 255));
        nomelb5.setText("NOME:");

        nomeprofessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeprofessorActionPerformed(evt);
            }
        });

        emaillb5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emaillb5.setForeground(new java.awt.Color(255, 255, 255));
        emaillb5.setText("E-MAIL:");

        senhalb5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        senhalb5.setForeground(new java.awt.Color(255, 255, 255));
        senhalb5.setText("SENHA:");

        senhaprofessor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        confirmasenhalb5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        confirmasenhalb5.setForeground(new java.awt.Color(255, 255, 255));
        confirmasenhalb5.setText("CONFIRME SENHA:");

        confirmasenha5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        cpflb5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cpflb5.setForeground(new java.awt.Color(255, 255, 255));
        cpflb5.setText("CPF:");

        telefonelb5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        telefonelb5.setForeground(new java.awt.Color(255, 255, 255));
        telefonelb5.setText("TELEFONE:");

        datanascimentolb5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        datanascimentolb5.setForeground(new java.awt.Color(255, 255, 255));
        datanascimentolb5.setText("DATA DE NASCIMENTO:");

        generolb5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        generolb5.setForeground(new java.awt.Color(255, 255, 255));
        generolb5.setText("GÊNERO:");

        masculino5.setBackground(new java.awt.Color(126, 153, 214));
        buttonGroup1.add(masculino5);
        masculino5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        masculino5.setForeground(new java.awt.Color(255, 255, 255));
        masculino5.setText("MASCULINO");
        masculino5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masculino5ActionPerformed(evt);
            }
        });

        feminino5.setBackground(new java.awt.Color(126, 153, 214));
        buttonGroup1.add(feminino5);
        feminino5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        feminino5.setForeground(new java.awt.Color(255, 255, 255));
        feminino5.setText("FEMININO");

        outro5.setBackground(new java.awt.Color(126, 153, 214));
        buttonGroup1.add(outro5);
        outro5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        outro5.setForeground(new java.awt.Color(255, 255, 255));
        outro5.setText("OUTRO");

        salvarbtn5.setText("SALVAR");
        salvarbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarbtn5ActionPerformed(evt);
            }
        });

        datanascimentolb8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        datanascimentolb8.setForeground(new java.awt.Color(255, 255, 255));
        datanascimentolb8.setText("SALÁRIO:");

        javax.swing.GroupLayout professorcadLayout = new javax.swing.GroupLayout(professorcad);
        professorcad.setLayout(professorcadLayout);
        professorcadLayout.setHorizontalGroup(
            professorcadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(professorcadLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(professorcadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(professorcadLayout.createSequentialGroup()
                        .addComponent(generolb5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(masculino5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(feminino5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outro5))
                    .addGroup(professorcadLayout.createSequentialGroup()
                        .addComponent(datanascimentolb5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datanascimentoprofessor, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(telefonelb5)
                    .addGroup(professorcadLayout.createSequentialGroup()
                        .addGroup(professorcadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cpflb5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(senhalb5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmasenhalb5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emaillb5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomelb5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(professorcadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailprofessor)
                            .addComponent(nomeprofessor)
                            .addGroup(professorcadLayout.createSequentialGroup()
                                .addGroup(professorcadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(telefoneprofessor, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(professorcadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(confirmasenha5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(senhaprofessor, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cpfprofessor, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)
                                .addComponent(salvarbtn5))))
                    .addGroup(professorcadLayout.createSequentialGroup()
                        .addComponent(datanascimentolb8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salario, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        professorcadLayout.setVerticalGroup(
            professorcadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(professorcadLayout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(professorcadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomelb5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeprofessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(professorcadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emaillb5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailprofessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(professorcadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhalb5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(senhaprofessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(professorcadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmasenha5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmasenhalb5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(professorcadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpflb5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfprofessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(professorcadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonelb5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefoneprofessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(professorcadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datanascimentolb5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datanascimentoprofessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(professorcadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datanascimentolb8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(professorcadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generolb5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(masculino5)
                    .addComponent(feminino5)
                    .addComponent(outro5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addComponent(salvarbtn5)
                .addGap(27, 27, 27))
        );

        jTabbedPane2.addTab("Professor", professorcad);

        disciplinacad.setBackground(new java.awt.Color(126, 153, 214));

        jPanel12.setBackground(new java.awt.Color(9, 62, 186));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("LA FACULDADE");

        jLabel14.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("CADASTRO DISCIPLINA");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nomedisciplinalb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nomedisciplinalb.setForeground(new java.awt.Color(255, 255, 255));
        nomedisciplinalb.setText("NOME:");

        nomedisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomedisciplinaActionPerformed(evt);
            }
        });

        duracaodisciplinalb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        duracaodisciplinalb.setForeground(new java.awt.Color(255, 255, 255));
        duracaodisciplinalb.setText("DURAÇÃO:");

        modalidadedisciplinalb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        modalidadedisciplinalb.setForeground(new java.awt.Color(255, 255, 255));
        modalidadedisciplinalb.setText("MODALIDADE:");

        masculino6.setBackground(new java.awt.Color(126, 153, 214));
        modalidadedisciplina.add(masculino6);
        masculino6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        masculino6.setForeground(new java.awt.Color(255, 255, 255));
        masculino6.setSelected(true);
        masculino6.setText("PRESENCIAL");
        masculino6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masculino6ActionPerformed(evt);
            }
        });

        feminino6.setBackground(new java.awt.Color(126, 153, 214));
        modalidadedisciplina.add(feminino6);
        feminino6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        feminino6.setForeground(new java.awt.Color(255, 255, 255));
        feminino6.setText("EAD");

        salvarbtn6.setText("SALVAR");
        salvarbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarbtn6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout disciplinacadLayout = new javax.swing.GroupLayout(disciplinacad);
        disciplinacad.setLayout(disciplinacadLayout);
        disciplinacadLayout.setHorizontalGroup(
            disciplinacadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(disciplinacadLayout.createSequentialGroup()
                .addGroup(disciplinacadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(disciplinacadLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(nomedisciplinalb, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(disciplinacadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomedisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salvarbtn6, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(disciplinacadLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(duracaodisciplinalb, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(duracaodisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(disciplinacadLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(modalidadedisciplinalb, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(masculino6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(feminino6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        disciplinacadLayout.setVerticalGroup(
            disciplinacadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(disciplinacadLayout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(disciplinacadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomedisciplinalb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomedisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(disciplinacadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(duracaodisciplinalb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duracaodisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(disciplinacadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modalidadedisciplinalb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(masculino6)
                    .addComponent(feminino6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 344, Short.MAX_VALUE)
                .addComponent(salvarbtn6)
                .addGap(27, 27, 27))
        );

        jTabbedPane2.addTab("Disciplina", disciplinacad);

        contatocad.setBackground(new java.awt.Color(126, 153, 214));
        contatocad.setEnabled(false);

        jPanel13.setBackground(new java.awt.Color(9, 62, 186));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("LA FACULDADE");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        resumo.setEditable(false);
        resumo.setColumns(20);
        resumo.setRows(5);
        jScrollPane2.setViewportView(resumo);

        listarbtn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LISTAR", "Alunos", "Cursos", "Salas", "Professores", "Disciplinas" }));
        listarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarbtnActionPerformed(evt);
            }
        });

        jButton1.setText("EXPORTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("*Adicione \".txt\" depois");

        jLabel15.setBackground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("de nomear o arquivo");

        javax.swing.GroupLayout contatocadLayout = new javax.swing.GroupLayout(contatocad);
        contatocad.setLayout(contatocadLayout);
        contatocadLayout.setHorizontalGroup(
            contatocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contatocadLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(listarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(contatocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel15))
                .addGap(41, 41, 41))
        );
        contatocadLayout.setVerticalGroup(
            contatocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contatocadLayout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(contatocadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contatocadLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contatocadLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(listarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contatocadLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)))
                .addContainerGap(232, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Exportar", contatocad);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome1ActionPerformed

    private void masculino1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masculino1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masculino1ActionPerformed

    private void nomealunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomealunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomealunoActionPerformed

    private void masculino2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masculino2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masculino2ActionPerformed

    private void nomecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomecursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomecursoActionPerformed

    private void presencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presencialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_presencialActionPerformed

    private void numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroActionPerformed

    private void masculino4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masculino4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masculino4ActionPerformed

    private void nomeprofessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeprofessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeprofessorActionPerformed

    private void masculino5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masculino5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masculino5ActionPerformed

    private void nomedisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomedisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomedisciplinaActionPerformed

    private void masculino6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masculino6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masculino6ActionPerformed

    private void salvarbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarbtn5ActionPerformed
        Professor p = new Professor(nomeprofessor.getText(),emailprofessor.getText(),String.valueOf(senhaprofessor.getPassword()));
        System.out.println("dale");
        Professor.addListaProfessor(p);
        Professor.getProfessores();
        
    }//GEN-LAST:event_salvarbtn5ActionPerformed

    private void salvarbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarbtn2ActionPerformed
        Aluno a = new Aluno(nomealuno.getText(),emailaluno.getText(),String.valueOf(senhaaluno.getPassword()));
        System.out.println("dale");
        Aluno.addListaAlunos(a);
        Aluno.getAlunos();
    }//GEN-LAST:event_salvarbtn2ActionPerformed

    private void salvarbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarbtn6ActionPerformed
        Disciplina d = new Disciplina(nomedisciplina.getText(),duracaodisciplina.getText(),String.valueOf(modalidadedisciplina.getSelection()));
        System.out.println("dale");
        Disciplina.addListaDisciplinas(d);
        Disciplina.getDisciplinas();
    }//GEN-LAST:event_salvarbtn6ActionPerformed

    private void salvarbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarbtn3ActionPerformed
        Curso c = new Curso(nomecurso.getText(),duracaocurso.getText(), String.valueOf(modalidadecurso.getSelection().getActionCommand()),descricaocurso.getText());
        System.out.println("dale");
        Curso.addListaCursos(c);
        Curso.getCursos();
    }//GEN-LAST:event_salvarbtn3ActionPerformed

    private void salvarbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarbtn4ActionPerformed
        
    
        Sala s = new Sala(numero.getText(),capacidade.getText(),andar.getText(), tiposala.getSelection().getActionCommand());
        System.out.println("dale");
        Sala.addListaSalas(s);
        Sala.getSalas();
    }//GEN-LAST:event_salvarbtn4ActionPerformed

    private void listarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarbtnActionPerformed
        if(listarbtn.getSelectedIndex()==0){
            resumo.setText("");
        }
        else if(listarbtn.getSelectedIndex()==1){
            resumo.setText(Aluno.getAlunos());
        }
        else if(listarbtn.getSelectedIndex()==2){
            resumo.setText(Curso.getCursos());
        }
        else if(listarbtn.getSelectedIndex()==3){
            resumo.setText(Sala.getSalas());
        }
        else if(listarbtn.getSelectedIndex()==4){
            resumo.setText(Professor.getProfessores());
        }
        else if(listarbtn.getSelectedIndex()==5){
            resumo.setText(Disciplina.getDisciplinas());
        }
    }//GEN-LAST:event_listarbtnActionPerformed

    private void duracaocursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duracaocursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duracaocursoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
if (fileChooser.showSaveDialog(jPanel6) == JFileChooser.APPROVE_OPTION) {
  File file = fileChooser.getSelectedFile();
  String path = file.getAbsolutePath();
  // save to file
  FileWriter fileWriter = null;
		try {
			fileWriter = new FileWriter(file);
			//inherited method from java.io.OutputStreamWriter 
			fileWriter.write(resumo.getText());
			
		} catch (Exception e) {
			e.printStackTrace();
		}finally {
			try {
				if (fileWriter != null) {
					fileWriter.flush();
					fileWriter.close();					
				}
			} catch (IOException e) {
				e.printStackTrace();
			}
                }
  
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void laboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laboratorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laboratorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel admincad;
    private javax.swing.JPanel alunocad;
    private javax.swing.JTextField andar;
    private javax.swing.JLabel andarlb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField capacidade;
    private javax.swing.JLabel capacidadelb;
    private javax.swing.JPasswordField confirmasenha1;
    private javax.swing.JPasswordField confirmasenha2;
    private javax.swing.JPasswordField confirmasenha5;
    private javax.swing.JLabel confirmasenhalb1;
    private javax.swing.JLabel confirmasenhalb2;
    private javax.swing.JLabel confirmasenhalb5;
    private javax.swing.JPanel contatocad;
    private javax.swing.JTextField cpf1;
    private javax.swing.JTextField cpfaluno;
    private javax.swing.JLabel cpflb1;
    private javax.swing.JLabel cpflb2;
    private javax.swing.JLabel cpflb5;
    private javax.swing.JTextField cpfprofessor;
    private javax.swing.JPanel cursocad;
    private javax.swing.JTextField datanascimento1;
    private javax.swing.JTextField datanascimentoaluno;
    private javax.swing.JLabel datanascimentolb1;
    private javax.swing.JLabel datanascimentolb2;
    private javax.swing.JLabel datanascimentolb5;
    private javax.swing.JLabel datanascimentolb8;
    private javax.swing.JTextField datanascimentoprofessor;
    private javax.swing.JTextArea descricaocurso;
    private javax.swing.JPanel disciplinacad;
    private javax.swing.JTextField duracaocurso;
    private javax.swing.JTextField duracaodisciplina;
    private javax.swing.JLabel duracaodisciplinalb;
    private javax.swing.JLabel duracaolb;
    private javax.swing.JRadioButton ead;
    private javax.swing.JTextField email1;
    private javax.swing.JTextField emailaluno;
    private javax.swing.JLabel emaillb1;
    private javax.swing.JLabel emaillb2;
    private javax.swing.JLabel emaillb3;
    private javax.swing.JLabel emaillb5;
    private javax.swing.JTextField emailprofessor;
    private javax.swing.JRadioButton feminino1;
    private javax.swing.JRadioButton feminino2;
    private javax.swing.JRadioButton feminino5;
    private javax.swing.JRadioButton feminino6;
    private javax.swing.JLabel generolb1;
    private javax.swing.JLabel generolb2;
    private javax.swing.JLabel generolb5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JRadioButton laboratorio;
    private javax.swing.JComboBox<String> listarbtn;
    private javax.swing.JRadioButton masculino1;
    private javax.swing.JRadioButton masculino2;
    private javax.swing.JRadioButton masculino4;
    private javax.swing.JRadioButton masculino5;
    private javax.swing.JRadioButton masculino6;
    private javax.swing.ButtonGroup modalidadecurso;
    private javax.swing.ButtonGroup modalidadedisciplina;
    private javax.swing.JLabel modalidadedisciplinalb;
    private javax.swing.JLabel modalidadelb;
    private javax.swing.JTextField nome1;
    private javax.swing.JTextField nomealuno;
    private javax.swing.JTextField nomecurso;
    private javax.swing.JLabel nomecursolb;
    private javax.swing.JTextField nomedisciplina;
    private javax.swing.JLabel nomedisciplinalb;
    private javax.swing.JLabel nomelb1;
    private javax.swing.JLabel nomelb2;
    private javax.swing.JLabel nomelb5;
    private javax.swing.JTextField nomeprofessor;
    private javax.swing.JTextField numero;
    private javax.swing.JLabel numerolb;
    private javax.swing.JRadioButton outro1;
    private javax.swing.JRadioButton outro2;
    private javax.swing.JRadioButton outro5;
    private javax.swing.JRadioButton presencial;
    private javax.swing.JPanel professorcad;
    private javax.swing.JTextArea resumo;
    private javax.swing.JPanel salacad;
    private javax.swing.JTextField salario;
    private javax.swing.JButton salvarbtn1;
    private javax.swing.JButton salvarbtn2;
    private javax.swing.JButton salvarbtn3;
    private javax.swing.JButton salvarbtn4;
    private javax.swing.JButton salvarbtn5;
    private javax.swing.JButton salvarbtn6;
    private javax.swing.JPasswordField senha1;
    private javax.swing.JPasswordField senhaaluno;
    private javax.swing.JLabel senhalb1;
    private javax.swing.JLabel senhalb2;
    private javax.swing.JLabel senhalb5;
    private javax.swing.JPasswordField senhaprofessor;
    private javax.swing.JTextField telefone1;
    private javax.swing.JTextField telefonealuno;
    private javax.swing.JLabel telefonelb1;
    private javax.swing.JLabel telefonelb2;
    private javax.swing.JLabel telefonelb5;
    private javax.swing.JTextField telefoneprofessor;
    private javax.swing.JLabel tipolb;
    private javax.swing.ButtonGroup tiposala;
    private javax.swing.JPasswordField valorcurso;
    private javax.swing.JLabel valorlb;
    // End of variables declaration//GEN-END:variables
}
